### PR TITLE
Dima tests

### PR DESCRIPTION
**Pull request by dmalarev**
I changed the logger, so it now has no parameters.
Can you check if everything is correct?

### CODE REVIEW

**Comment by dmalarev** [comment]
changed it so the unused methods are deleted <organization

**Comment by ClintonCao** [comment]
I am getting NullpointerExceptions when I click on either Menu button or the the quit button without actually playing the game. This is because in the Game.java, there is no Logger instantiated, therefore causing the NullPointerExceptions. The rest seems fine to me, as there wasn't any big changes. <bug

**Comment by dmalarev** [comment]
I have noticed the bug, but have not found where exactly to initialize it, as when I put it in the start() method, the bug persists.
<review

**Comment by ClintonCao** [comment]
Well one way is to make a new field in Game.java and everywhere the logger is supposed to log an action, you use a getter (from the Game class) to do the its job. Hope that is clear enough. <bug,review

**Comment by ClintonCao** [comment]
As the conflicts has been solved on a different branch, this pull request will now be closed. <review

**Pull request closed without merging**
