### PR TITLE
Temp merge

### PR DESCRIPTION
**Pull request by Michieldoesburg**
Sunwei's Singleton implementation has been merged into this branch. Checkstyle warnings are at 13, which are all temporary (fixing them requires big changes).

### CODE REVIEW

**Comment by ClintonCao** [comment]
The code in the MainScreenController is much shorter, now that we have the factories. Although I am not sure if it's good to make a factory for the animation timer, as it calls many methods from the MainScreenController. But it does make MainScreenController easier to read.

 I think maybe you should write out the whole name for the eventhandlers, as it was pointed out by the TA that using abbreviation makes the class unclear. 

Please fix the indentation on the new classes and indeed the VisibilityModifiers warnings will be gone once the class is further refactored.

Nice job! <layout, naming, organisation, review

**Comment by ClintonCao** [comment]
P.S. Don't forget to add the name after @param  LosingScreenEHFactoryInterface. <layout

**Comment by Michieldoesburg** [comment]
Youre right about the class abbreviations I think. Initially I felt the class names might be too long, but abbreviating just makes them more unclear anyways.

**Comment by Michieldoesburg** [comment]
I think we can leave animationtimer a factory for now. It does interact a lot with mainscreencontroller at the moment, but that is due for change.

**Comment by ClintonCao** [comment]
Yeah we could do that for now. <organisation

**Comment by ClintonCao** [comment]
This will now be merged onto master. <review

**Pull request merged**
