### PR TITLE
Abstract Factory Design Pattern Removed + Sprint Documents + New Pom Version. < documentation, organisation

### PR DESCRIPTION
**Pull request by ClintonCao**
The abstract factory and the factory producer is now removed. This was because they violated a design principle.

I've also added the sprint reflection 5 and also changed the pom version to the last version.

### CODE REVIEW

**Comment by Michieldoesburg** [comment]
Looks good clintoni :dancer:. In the end this abstract factory stuff wasnt doing anything for us ( in fact making the situation worse ). So there was no sense in keeping it. < review

**Comment by SunweiWang** [comment]
After this modification, we only have 58 classes now, this prevented us from almost breaking Liskov substitution principle, and simplified our code. Good job with implementation, Clinton, :+1: 
< review, organisation

**Comment by ClintonCao** [comment]
I think we broke the Liskov Substitution Principle in the previous version. Shall I merge it then?

**Comment by SunweiWang** [comment]
I will merge this.

**Pull request merged**
