### PR TITLE
Abstract factory < feature, organisation

### PR DESCRIPTION
**Pull request by MatthijsJWH**
Implemented the Abstract Factory Method into the Game.
<organisation.

### CODE REVIEW

**Comment by ClintonCao** [comment]
Nice job with the abstract factory! I understand what the "empty" methods are supposed to do in the subclasses, but I still find that it is kinda weird. But otherwise it would be hard to implement the superclass. 

For me it looks good, but please fix the remaining checkstyle warnings (missing javadoc). < documentation, organisation, feature

**Comment by ClintonCao** [comment]
P.S. Don't forget to explain the implementation in the report.

**Comment by MatthijsJWH** [comment]
I hope this covers all the missing JavaDocs, maven doesn't wan't to work for me.
<documentation.

**Comment by ClintonCao** [comment]
You managed to fix 2 out of 6 warnings, the remaining 4 are all the abstract methods. They also need documentation. < documentation

**Comment by MatthijsJWH** [comment]
Aha, I will get right on it.

**Comment by MatthijsJWH** [comment]
The last four missing javadocs should now also be fixed.
<documentation.

**Comment by ClintonCao** [comment]
Yes it did! I think we are read to merge this, any other comments? < documentation

**Comment by MatthijsJWH** [comment]
Also @ClintonCao I made the explenation of the implementationa and the sequence diagram and they are in the report. So if somebody could check if they suffice that would be great.

**Comment by MatthijsJWH** [comment]
Otherwise please send me a message on whatsapp, because then I know that I need to go back home after training to improve it.

**Comment by ClintonCao** [comment]
Yes I will take a look at it, as soon as I am done with the diagrams.

**Comment by Michieldoesburg** [comment]
Nice changes, code looks good and it runs perfectly well on my machine so I say we merge < review

**Comment by SunweiWang** [comment]
Well implemented with abstract factory, I'm gonna to merge this.
< review, organisation

**Pull request merged**
