### PR TITLE
Redesigned The Option Screen. <user-interface

### PR DESCRIPTION
**Pull request by ClintonCao**

### CODE REVIEW

**Comment by SunweiWang** [comment]
Nicely done on the detailed instruction for Sharkelli.
< review

**Comment by SunweiWang** [comment]
o, btw, @ClintonCao , I don't see the picture of bomb in the option screen anymore, is it intend that way?

**Comment by ClintonCao** [comment]
@SunweiWang My bad, must have removed it by accident. Will be adding it back in a minute! <user-interface

**Comment by ClintonCao** [comment]
I added back the original file path, please if it is correct! < user-interface

**Comment by SunweiWang** [comment]
I can see bomb again in the option screen now, also the colorful spear, looks nice.
< user-interface, review

**Comment by Michieldoesburg** [comment]
I had a quick look, and it looks very good.

**Pull request merged**
