### PR TITLE
Reconfigured Maven Project. <configuration

### PR DESCRIPTION
**Pull request by ClintonCao**
I reconfigured all the packages of Fishy to how it is supposed to be on Maven. I highly recommend merging this pull request before anyone start working on new things!

### CODE REVIEW

**Comment by ClintonCao** [comment]
There seems to be an issue with the missing src folder, I will try to solve this problem.

**Comment by ClintonCao** [comment]
The problem has been fixed! <configuration

**Comment by SunweiWang** [comment]
Nicely done on the reconfiguration of packages of Fishy,
< review, configuration

**Comment by Michieldoesburg** [comment]
This works fine for me and we were very  much in need of some cleaning up of the project files :chart_with_upwards_trend:

**Pull request merged**
