### PR TITLE
Add more test methods to our test classes  < testing

### PR DESCRIPTION
**Pull request by SunweiWang**

### CODE REVIEW

**Comment by SunweiWang** [comment]
BoundingBox class now has 100% test coverage.
< testing

**Comment by MatthijsJWH** [comment]
Have you checked the maven site for pmd and fixbugs to see if their aren't any mistakes we can easily fix?
< review

**Comment by ClintonCao** [comment]
I've ran a Maven clean and then a Maven build, it seems that the warnings on assertTrue and assertFalse are gone. Nice job on the fixing the pmd warning. However, there's a checkstyle warning on line 71 (run Maven to find the exact problem). < testing,  review

**Comment by SunweiWang** [comment]
Thanks, Clinton, I fixed the checkstyle warning, and yes Matthijs, I also ran pmd and findbugs on the code. 
< review, testing

**Comment by ClintonCao** [comment]
I will merge it then!

**Pull request merged**
