### PR TITLE
Removed unused parameter from the class. < organisation

### PR DESCRIPTION
**Pull request by ClintonCao**
I removed an unused parameter for the class of Lance. <organisation

### CODE REVIEW

**Comment by SunweiWang** [comment]
Nice, now we removed a parameter which we don't use, we have cleaner code.
< review, organisation

**Comment by Michieldoesburg** [comment]
Ah yes this is a good change < review

**Comment by ClintonCao** [comment]
I fixed the merge conflicts!

**Comment by Michieldoesburg** [comment]
Well then let's merge < review

**Pull request merged**
