### PR TITLE
Removed Wrong Information On OptionScreen < user-interface

### PR DESCRIPTION
**Pull request by ClintonCao**
I removed the wrong information regarding the amount of bombs the player has when the game is started. I also updated the gitignore to ignore the highscore file.

### CODE REVIEW

**Comment by Michieldoesburg** [comment]
You have the heart images which were just merged in the other branch in here? :dancer:

**Comment by ClintonCao** [comment]
That is right, I wanted to add the image to the screen, because I didn't know when the other pull request was going to be merged. I do agree that it was a bit redundant < user-interface

**Comment by Michieldoesburg** [comment]
Can you remove the files? Because they are already on the git now.

**Comment by SunweiWang** [comment]
In the option screen, "You can get more lifes by collecting hearts that appears on the screen.", shouldn't "appears" be "appear"?
< review

**Comment by ClintonCao** [comment]
Yes you are right! My bad!

**Comment by ClintonCao** [comment]
Fixed!

**Pull request merged**
