### PR TITLE
Applying Singleton design pattern to the game

### PR DESCRIPTION
**Pull request by SunweiWang**
< organisation

### CODE REVIEW

**Comment by SunweiWang** [comment]
I have finished applying Singleton design pattern to PlayerFish and Logger classes, however, I would not apply Singleton to Logger class, since it makes testing Logger class close to impossible. PlayerFish class on the other hand is special in our implementation, we used an unique way to test, so it is depended on Game class, making it an singleton class does not affect its testing.

**Comment by SunweiWang** [comment]
Would appreciate opinions from everyone, suggestions or disagreements.
< review

**Comment by Michieldoesburg** [comment]
PlayerFish looks good. So are we making logger singleton or not, because it is singleton now?

**Comment by ClintonCao** [comment]
Umm am I the only one that can't see any difference in the code? Even after pulling.. <organisation

**Comment by SunweiWang** [comment]
Yes, Logger is a Singleton now, but so far I cannot find a good way to test it. If you guys agrees, I would revert Logger class back, since JUnit test case is not working now for Logger.
< testing

**Comment by SunweiWang** [comment]
Clinton, you can just view the differences directly from Github, anyway, did you checkout to single branch?

**Comment by ClintonCao** [comment]
Nevermind, I see them now. Did you realized that the class is still final?

**Comment by SunweiWang** [comment]
Yes, I know Logger class is still final, since it cannot be extended by any other class.
And final or not, it does affect unit testing case.
And about two threads might enter the method at the same time, I will fix that, but shall I just revert the Logger class to its original state?

**Comment by ClintonCao** [comment]
I made a new test class for logger on my local single branch. In my case all the test passed, so I have no idea why yours did not? I also noticed that If I modified some test in your test class, nothing changes.

**Comment by SunweiWang** [comment]
O, Clinton, did you just run the test on the entire Fish folder, so you started the game, I guess that's why the test passed, but if you just run the LoggerTest individually, it won't. 

I made LoggerTest as an unit test, so it will still work without starting the game, so that's why I was frustrated about the tests won't work after applying Singleton pattern to Logger class.

**Comment by ClintonCao** [comment]
No I did not. I made LoggerTest2 and just run it as an individual test class. I even pasted your code and it still worked fine. <testing

**Comment by SunweiWang** [comment]
ehh, that's really weird, does this work on any other ones' laptop, if does, I probably will look into change this laptop...

**Comment by ClintonCao** [comment]
So it seems like that the test does not fail anymore? I can also run it as individual test class and it still passes for me. So I guess we are keeping the singleton pattern for Logger. <testing

**Comment by ClintonCao** [comment]
You should use the same name after @param (so the name must match with the method variable name). If you give it a wrong name, it causes errors when you try to do a maven build. Also there are still quite some checkstyle warnings. <configuration

**Comment by SunweiWang** [comment]
Warnings fixed as well, and thanks Clinton for your suggestions, please review it, and if it's okay, it's ready to merge.
< review

**Comment by ClintonCao** [comment]
Nice job, most of the warnings has been fixed. The remaining 5 warnings are from Game, but this class will be refactored soon. So this pull request can be merged. Any comments from the others? <layout, review

**Comment by Michieldoesburg** [comment]
This is good, merged!

**Pull request merged**
