### PR TITLE
Life item

### PR DESCRIPTION
**Pull request by Michieldoesburg**

### CODE REVIEW

**Comment by ClintonCao** [comment]
Very nice Implementation. Seems to be working fine, beside that it can reach to 4? The max is three in our requirements < review, feature

**Comment by Michieldoesburg** [comment]
Youre right I fixed it < review

**Comment by SunweiWang** [comment]
It looks really good man, now the player can only get maximum 4 lives, but as Clinton stated, it was 3 in our requirements, and we have a merge conflict from Matthijs's implementation.
< review

**Comment by Michieldoesburg** [comment]
Okay, fixed the merge conflicts and player can only get 3 lives now.

**Comment by ClintonCao** [comment]
Nice, I will merge it!

**Pull request merged**
