### PR TITLE
Fixed checkstyle warnings & modified pom. <layout

### PR DESCRIPTION
**Pull request by ClintonCao**
Fixed warnings with the imports and also changed the linelength for
checkstyle. Also removed a property from the pom file. jdk 1.7 is not
used.

### CODE REVIEW

**Comment by Michieldoesburg** [comment]
Good fixes on the checkstyle. We can finally stop breaking up lines.

**Comment by SunweiWang** [comment]
nice fix, but for me, on the import java.net.URL,
it still gives checkstyle warning:
Wrong lexicographical order for import.
<layout

**Comment by ClintonCao** [comment]
I can't seem to find the warning that you are having, can you please give me the exact class?
<layout

**Comment by SunweiWang** [comment]
The warnings for me are shown in all screen controller classes, including MainScreenController, LosingScreenController, OptionsController, WinningScreenController.

**Comment by ClintonCao** [comment]
I still don't seem to find those warnings. But you can merge it then.
<layout

**Pull request merged**
