### PR TITLE
Fixed Test for PlayerFish. < testing

### PR DESCRIPTION
**Pull request by ClintonCao**
With the help of TestFX, the PlayerFishTest, can now be moved to
the test folder!

### CODE REVIEW

**Comment by ClintonCao** [comment]
I manged to fix the configurations on travis, however, if you look at the build log on travis, you can see an exception has been thrown. This is due to the env not supporting MP3 files. 

We can either ignore this whole pull request or we can merge it.

In my opinion I find the exception a bit ugly. <configuration

**Comment by SunweiWang** [comment]
I saw the MediaException in the travis build, and I agree with you. However, this pull request indeed solve the problem of PlayerFishTest being in the wrong place. There is just one more thing I think that's worth notice, if I run the JUnit test on the the whole fish project, everything passes, but there is no coverage shown anymore.
< review

**Comment by ClintonCao** [comment]
@SunweiWang Check if you there is no JUnit 4.12 and JavaFX SDK library in the whole folder of FIshy. Because you are supposed to have only the Maven Dependencies and JRE System Library. Having the other two cause eclemma not showing the coverage. < testing

**Comment by Michieldoesburg** [comment]
So whats the status on this? Are there still problems?

**Comment by ClintonCao** [comment]
Well that was only with Sunwei, can you also check if you can see the coverage @Michieldoesburg. There is just one problem, which is the exception in the build log. But that is because the environment does not support mp3 files.

**Pull request merged**
