### PR TITLE
Added OptionsScreenEventHandlerFactory and WinningScreenEventHandlerF…

### PR DESCRIPTION
**Pull request by Michieldoesburg**
…actory, with their interfaces. < organisation

### CODE REVIEW

**Comment by MatthijsJWH** [comment]
We might need to do so for the report Sunwei.
It looks good to me, I'm only a bit worried about how to implement the abstract factory design pattern (which is/might be needed now that we have so many factories).
Anybody have ideas on that.
< review, organisation

**Comment by Michieldoesburg** [comment]
I dont think changing requirements after the fact will help much sunwei (and its also not really in the spirit of a contract).

Matthijs what do you mean exactly? I dont really understand.

**Comment by ClintonCao** [comment]
They requirements were only for the Logger and PlayerFish, the new singleton classes was just extras that we did for this sprint. Also it is too late to change the requirements as it has been already approved by the TA. @Matthijs I'm not sure if we would like to do that, as it is an extra design pattern that we threw in for this sprint. But it is on the should haves of the requirements, so I am having doubts on what action to take. <review, organisation

**Comment by MatthijsJWH** [comment]
Pretty much the abstract factory pattern is an extension of the factory pattern, which basiccaly means that you have an abstract factory class which all others are programmed against and next to that you need to have a "factory factory". It isn't that complicated but it does mean changing nearly all factories we have up till now. < review, organisation

**Comment by Michieldoesburg** [comment]
hmmm it sounds interesting, maybe something to consider for next sprint. For this sprint it would be too much i feel.

**Comment by MatthijsJWH** [comment]
Yeah I think so too, but for now I have no further remarks on this pull request, shall we merge it?

**Comment by ClintonCao** [comment]
I am fine with the pull request. Did anyone run a maven build on this pull request?

**Comment by Michieldoesburg** [comment]
uhh im not sure i did and on a train right now, if someone could check it quickly, that would be great.

**Comment by ClintonCao** [comment]
I ran Maven and there are of course the visibility modifiers warnings but also the finalclass warning. We can ignore this, if everyone agree. <review, organisation

**Comment by MatthijsJWH** [comment]
Sure, if we can merge it than I can finish my part without any merge conflicts.

**Comment by Michieldoesburg** [comment]
okey lets merge it then

**Pull request merged**
