### PR TITLE
Fixing the problem that console prints enter losing screen twice + fi…

### PR DESCRIPTION
**Pull request by SunweiWang**
…xing a bit checkstyle

<bug, layout

### CODE REVIEW

**Comment by SunweiWang** [comment]
This commit is just a part of creating logger for buttons on the menus, Exercise 3, Task 3 on Requirement Logger. And fixed some checkstyle error, still work in progress, so no need to merge now.
<bug, layout

**Comment by SunweiWang** [comment]
I finished my part of the logger implementation as well, 
the only question I have is that is it necessary to log each key press? Because it is constantly printing in the console, and quite annoying.

p.s. Can someone also have a look at this branch.

**Comment by ClintonCao** [comment]
Also I forgot to say, it is necessary to log all key events, as it is in the requirements of the logger. <logic

**Comment by SunweiWang** [comment]
Okay, sure, I fixed the naming issues of the methods.
And sure the key events are in the requirement.
< naming, logic

**Pull request merged**
