### PR TITLE
Added Documents For Assignment 3 + Diagrams.

### PR DESCRIPTION
**Pull request by ClintonCao**
<documentation

### CODE REVIEW

**Comment by SunweiWang** [comment]
Nice UML diagram, in the report, under factory design pattern third line, last word, "does" should be replaced by "do". 
< review

**Comment by ClintonCao** [comment]
Thanks Sunwei!, must have overlooked it.

**Comment by Michieldoesburg** [comment]
Looks fine to me, particularly nice work on the diagrams!

**Comment by ClintonCao** [comment]
Merging it to the master!

**Pull request merged**
