### PR TITLE
Added FishySmokeTest. < testing, configuration

### PR DESCRIPTION
**Pull request by ClintonCao**
As we are testing GUI elements with the PlayerFishTest, I decided to
create a smoke test, and in this test class some properties of PlayerFish
are tested. I also changed the configuration of Travis, as for some reason, Travis cannot find the button to click. Travis now completely skips the tests. (This is a bit dirty, but this is the only way that I know how to solve the issue.) If anyone can find a alternative solution, you are welcome to do so.

### CODE REVIEW

**Comment by dmalarev** [comment]
So far it looks good and i can see the coverage has gone up quite a bit.
As soon as the others agree, this will be merged < review

**Comment by ClintonCao** [comment]
I've added some new tests, and also fixed some of the pmd warnings ( javaFx related and some other that says that there are too many methods). < testing

**Comment by dmalarev** [comment]
Nicely done with the new tests and the PMD suppression. < review

**Comment by Michieldoesburg** [comment]
This is some excellent stuff. I say we can merge < review

**Comment by SunweiWang** [comment]
The implementation of SmokeTest really increased our coverage, and I aggree that we can merge.
< review, testing.

**Comment by ClintonCao** [comment]
Well let's merge!

**Pull request merged**
