### PR TITLE
Adding Life class to the game < feature

### PR DESCRIPTION
**Pull request by SunweiWang**

### CODE REVIEW

**Comment by Michieldoesburg** [comment]
Why did you add another image field to Life class? The Sprite field in superclass Item already has an Image field.

**Comment by SunweiWang** [comment]
You are right, I removed the image field from it, it was kind of redundant.
< review

**Comment by Michieldoesburg** [comment]
I can still the field in the class? < review

**Comment by SunweiWang** [comment]
Where exactly do you mean? can you put you comment next to the code?

**Comment by ClintonCao** [comment]
Indeed @Michieldoesburg. @SunweiWang  he meant the attribute image.  < review

**Comment by Michieldoesburg** [comment]
Yes, but the travis build is failing now

**Comment by SunweiWang** [comment]
Okay, I ran again a previous successful build, and it fails again now, I think it has something to do with the new merge to the master branch, but not really sure where exactly the problem is.

**Comment by SunweiWang** [comment]
Okay, finally fixed travis build, I think the problem was because some methods in the master branch has been replaced, and what is in the branch cannot be updated to master branch, so I merged the master into this branch and refactored some of my code.
< bug

**Comment by Michieldoesburg** [comment]
Okay nice.

**Pull request merged**
