### PR TITLE
Improving Logger and write LoggerTest file

### PR DESCRIPTION
**Pull request by SunweiWang**
< feature, testing

### CODE REVIEW

**Comment by SunweiWang** [comment]
This branch solved the merge conflicts while contains the change to Logger and the new LoggerTest file

**Comment by ClintonCao** [comment]
Nice job fixing the conflicts in the other pull request. That branch is now closed and any further changes to the logger should be committed to this pull request. <review

**Comment by ClintonCao** [comment]
Hey everyone, this pull request contains both the New Game+ mode and the changes in the logger class.  Can someone please review this pull request? <feature, bug, testing

**Comment by SunweiWang** [comment]
The branch is nicely merged, all the functions in the original branches are still here. The New Game+ mode is also well made, however, in order to get to New Game+ mode, I had to change the winning size from 400 to 80, otherwise it was really hard for me to win the game, maybe you guys play better than me,

**Comment by ClintonCao** [comment]
That is right. If we use a small size, then the game will be over very quickly. The game should give the player some challenge ;-). <feature

**Comment by MatthijsJWH** [comment]
Everything looks fine to me, do you want me to merge it?

**Comment by ClintonCao** [comment]
If there aren't any other problems or questions, you may merge it. <feature,testing, bug

**Comment by MatthijsJWH** [comment]
Then I will merge it.

**Pull request merged**
