### PR TITLE
Added New Sprite Images For New Feature <feature

### PR DESCRIPTION
**Pull request by ClintonCao**
I added the images for Sharkelli, Fish Knight and the Sword item. 
I also changed one line in the pom.xml. This fixes some of the warnings
that we get when we run a maven build.

### CODE REVIEW

**Comment by SunweiWang** [comment]
Nice fix in the pom file, and good pictures of Fish Knights. :+1: 
I'm just not so sure about the picture of Sharkelli.

**Comment by Michieldoesburg** [comment]
Sharkelli looks great imo

**Comment by dmalarev** [comment]
i agree with Michiel, it looks great

**Comment by ClintonCao** [comment]
I can send an email to Valentine to check with her if I was taking it too far?

**Comment by Michieldoesburg** [comment]
Pfft its not too far

**Comment by ClintonCao** [comment]
Well we are putting our boss's face on one op sprite in our game. He may feel offended.

**Comment by dmalarev** [comment]
I don't think it would be an issue.

**Comment by ClintonCao** [comment]
Well @MatthijsJWH you are the tie-breaker here. What do you think?

**Comment by Michieldoesburg** [comment]
Just send an email then @ClintonCao

**Comment by ClintonCao** [comment]
I have talked to Valentine about the image for Sharkelli. She said that it is fine, other groups had also done the same. <feature

**Comment by MatthijsJWH** [comment]
I think the image of sharkelli is fine, I don't know what else people had in mind.

**Comment by SunweiWang** [comment]
Sounds good to me then, but @ClintonCao , can you please also add a SharkelliRight, which would be useful for the End Boss class, would appreciate that.
< review

**Comment by ClintonCao** [comment]
@SunweiWang @Michieldoesburg   are we going to spawn the end boss from both direction of the screen or just one? If we are going to spawn it on both side, then I will be adding the other image. <feature

**Comment by dmalarev** [comment]
Perhaps right now it would be wise to just add the other as well, just in case we are going to spawn it from both directions.

**Comment by ClintonCao** [comment]
That is true, better safe than sorry. I added the right image for sharkelli! <feature

**Comment by Michieldoesburg** [comment]
Yeah I was thinking wed spawn it on one side and then let it criss cross the screen until its dead.

Anyways, since we all agree on the pictures, lets merge.

**Pull request merged**
