### PR TITLE
Composite design pattern < feature, organisation

### PR DESCRIPTION
**Pull request by Michieldoesburg**
Implemented composite design pattern.

### CODE REVIEW

**Comment by ClintonCao** [comment]
Very nice! This makes some of the methods in MainScreenController shorter, now that we don't have to keep a list of EnemyFish in the MainScreenController, but rather an object. MainScreenController now interacts with just one object, instead of multiple EnemyFish objects that we store in the MainScreenController. < feature, organisation, review

**Comment by Michieldoesburg** [comment]
Hahaha okay ill change it!

**Comment by Michieldoesburg** [comment]
Ive fixed the issue < documentation, configuration

**Comment by ClintonCao** [comment]
Nice, I will merge it to master then!

**Pull request merged**
